[package]
name = "ports_open-rs"
version = "0.1.0"
authors = ["lgraham076"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num_cpus = "1.13.0"
